use std::fs;
use std::path::Path;
use std::process::{Command, ExitCode, Stdio};

use crate::{error, hint, ok, Config};

use super::manifest::Manifest;
use super::spec::ProjectSpec;

enum LockStatus {
    Updated,
    Failed(String),
}

pub(super) fn write_project(
    manifest: &Manifest,
    target: &Path,
    flake: &str,
    project: &str,
    spec: &ProjectSpec,
    force: bool,
    source_url: &str,
    config: Config,
) -> Result<(), ExitCode> {
    fs::create_dir_all(target).map_err(|err| {
        error(config, &format!("failed to create {}: {err}", target.display()));
        ExitCode::from(1)
    })?;

    let flake_path = target.join("flake.nix");
    if flake_path.exists() && !force {
        match fs::read_to_string(&flake_path) {
            Ok(text) if text.contains("mkProjectFlakeFromManifest") => {}
            _ => {
                error(config, &format!("{} does not look generated by robo-nix", flake_path.display()));
                hint(config, "rerun with --force only if you want robo to replace it");
                return Err(ExitCode::from(1));
            }
        }
    }

    write_file(&flake_path, flake, config)?;
    write_file(&target.join("robo.nix"), project, config)?;
    write_file(&target.join(".python-version"), &spec.python_version, config)?;
    let pyproject = target.join("pyproject.toml");
    let pyproject_status = if pyproject.exists() {
        "kept"
    } else {
        write_file(&pyproject, &render_pyproject(spec), config)?;
        "wrote"
    };

    for component in &spec.components {
        let Some(component) = manifest.components.get(component) else {
            continue;
        };
        for dir in &component.scaffold_directories {
            fs::create_dir_all(target.join(dir)).map_err(|err| {
                error(config, &format!("failed to create {}: {err}", target.join(dir).display()));
                ExitCode::from(1)
            })?;
        }
    }

    register_git(target, &["flake.nix", "robo.nix", ".python-version", "pyproject.toml"]);
    let lock_status = update_flake_lock(target);
    if matches!(lock_status, LockStatus::Updated) {
        register_git(target, &["flake.lock"]);
    }
    print_summary(target, spec, pyproject_status, source_url, lock_status, config);
    Ok(())
}

fn write_file(path: &Path, text: &str, config: Config) -> Result<(), ExitCode> {
    fs::write(path, format!("{}\n", text.trim_end())).map_err(|err| {
        error(config, &format!("failed to write {}: {err}", path.display()));
        ExitCode::from(1)
    })
}

fn register_git(target: &Path, paths: &[&str]) {
    let inside = Command::new("git")
        .arg("-C")
        .arg(target)
        .arg("rev-parse")
        .arg("--is-inside-work-tree")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|status| status.success());
    if inside {
        let _ = Command::new("git")
            .arg("-C")
            .arg(target)
            .args(["add", "--intent-to-add", "--"])
            .args(paths)
            .status();
    }
}

fn update_flake_lock(target: &Path) -> LockStatus {
    match Command::new("nix")
        .arg("flake")
        .arg("lock")
        .arg("--update-input")
        .arg("robo-nix")
        .current_dir(target)
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .output()
    {
        Ok(output) if output.status.success() => LockStatus::Updated,
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let detail = stderr
                .lines()
                .rev()
                .find(|line| line.trim_start().starts_with("error:"))
                .or_else(|| stderr.lines().rev().find(|line| !line.trim().is_empty()))
                .unwrap_or("nix flake lock failed")
                .trim()
                .to_string();
            LockStatus::Failed(detail)
        }
        Err(err) => LockStatus::Failed(format!("failed to run nix flake lock: {err}")),
    }
}

fn shell_quote(path: &Path) -> String {
    let text = path.display().to_string();
    format!("'{}'", text.replace('\'', "'\"'\"'"))
}

fn print_summary(
    target: &Path,
    spec: &ProjectSpec,
    pyproject_status: &str,
    source_url: &str,
    lock_status: LockStatus,
    config: Config,
) {
    eprintln!("{} init", crate::label(config, "robo", crate::LabelKind::Status));
    eprintln!("  target: {}", target.display());
    eprintln!("  env:    {}", spec.env_name);
    eprintln!("  source: {source_url}");
    if !spec.probe_notes.is_empty() {
        eprintln!();
        eprintln!("Detected:");
        for note in &spec.probe_notes {
            eprintln!("  + {note}");
        }
    }
    print_suggestions(spec);
    eprintln!();
    ok(config, "Generated:");
    eprintln!("  wrote {}", target.join("flake.nix").display());
    eprintln!("  wrote {}", target.join("robo.nix").display());
    eprintln!("  wrote {}", target.join(".python-version").display());
    eprintln!("  {pyproject_status} {}", target.join("pyproject.toml").display());
    match lock_status {
        LockStatus::Updated => eprintln!("  updated {}", target.join("flake.lock").display()),
        LockStatus::Failed(message) => {
            eprintln!("  skipped {}", target.join("flake.lock").display());
            hint(
                config,
                &format!(
                    "run `(cd {} && nix flake lock --update-input robo-nix)` when Nix is available; {message}",
                    shell_quote(target)
                ),
            );
        }
    }
    eprintln!();
    eprintln!("{} Next steps:", crate::label(config, "robo", crate::LabelKind::Status));
    eprintln!("  (cd {} && robo check)", shell_quote(target));
    eprintln!("  robo sync --group dev");
    eprintln!("  robo run pytest tests");
}

fn print_suggestions(spec: &ProjectSpec) {
    if spec.suggestions.is_empty() && spec.component_suggestions.is_empty() {
        return;
    }
    eprintln!();
    eprintln!("Suggestions:");
    for item in &spec.suggestions {
        eprintln!("  ? {} {}: {}", item.kind, item.path, item.reason);
    }
    for item in &spec.component_suggestions {
        eprintln!("  ? component {}: {}; {}", item.name, item.reason, item.evidence);
    }
}

pub(super) fn render_flake(source_url: &str) -> String {
    format!(
        r#"{{
  inputs.robo-nix.url = "{}";

  # NOTE: generated plumbing. Most users should edit robo.nix,
  # pyproject.toml, and .python-version instead of this file.
  outputs = {{robo-nix, ...}}:
    robo-nix.lib.mkProjectFlakeFromManifest ./robo.nix;
}}"#,
        escape_nix(source_url)
    )
}

pub(super) fn render_project(spec: &ProjectSpec) -> String {
    let mut text = format!(
        r#"{{
  schemaVersion = 1;
  envName = "{}";
  description = "{}";
  components = [
{}
  ];
  pythonVersion = "{}";
  supportedSystems = [
{}
  ];
  workspaceRoot = "{}";"#,
        escape_nix(&spec.env_name),
        escape_nix(&spec.description),
        render_list(&spec.components),
        escape_nix(&spec.python_version),
        render_list(&spec.supported_systems),
        escape_nix(&spec.workspace_root)
    );
    if let Some(version) = &spec.cuda_wheel_version {
        text.push_str(&format!("\n  cudaWheelVersion = \"{}\";", escape_nix(version)));
    }
    if !spec.required_dirs.is_empty() {
        text.push_str(&format!("\n\n  requiredDirectories = [\n{}\n  ];", render_list(&spec.required_dirs)));
    }
    if !spec.required_files.is_empty() {
        text.push_str(&format!("\n\n  requiredFiles = [\n{}\n  ];", render_list(&spec.required_files)));
    }
    if !spec.env.is_empty() {
        text.push_str("\n\n  shellInit = ''\n");
        for item in &spec.env {
            if let Some((name, value)) = item.split_once('=') {
                text.push_str(&format!("    export {}=\"{}\"\n", name, value));
            }
        }
        text.push_str("  '';");
    }
    if !spec.source_scripts.is_empty() {
        text.push_str("\n\n  bootstrap = ''\n");
        for script in &spec.source_scripts {
            text.push_str(&format!("    . \"$WORKSPACE_ROOT/{}\"\n", script));
        }
        text.push_str("  '';");
    }
    {
        text.push_str("\n\n  provenance = {\n");
        text.push_str("    generatedBy = \"robo init\";\n");
        text.push_str(&format!("    profile = \"{}\";\n", escape_nix(&spec.profile_name)));
        if !spec.component_provenance.is_empty() {
            text.push_str("    componentReasons = [\n");
            for item in &spec.component_provenance {
                text.push_str("      {\n");
                text.push_str(&format!("        name = \"{}\";\n", escape_nix(&item.name)));
                text.push_str(&format!("        source = \"{}\";\n", escape_nix(&item.source)));
                text.push_str(&format!("        reason = \"{}\";\n", escape_nix(&item.reason)));
                text.push_str("      }\n");
            }
            text.push_str("    ];\n");
        }
        if !spec.probe_notes.is_empty() {
            text.push_str("    inferred = [\n");
            for note in &spec.probe_notes {
                text.push_str(&format!("      \"{}\"\n", escape_nix(note)));
            }
            text.push_str("    ];\n");
        }
        if !spec.suggestions.is_empty() {
            text.push_str("    suggestions = [\n");
            for item in &spec.suggestions {
                text.push_str("      {\n");
                text.push_str(&format!("        kind = \"{}\";\n", escape_nix(&item.kind)));
                text.push_str(&format!("        path = \"{}\";\n", escape_nix(&item.path)));
                text.push_str(&format!("        reason = \"{}\";\n", escape_nix(&item.reason)));
                text.push_str("      }\n");
            }
            text.push_str("    ];\n");
        }
        if !spec.component_suggestions.is_empty() {
            text.push_str("    componentSuggestions = [\n");
            for item in &spec.component_suggestions {
                text.push_str("      {\n");
                text.push_str(&format!("        name = \"{}\";\n", escape_nix(&item.name)));
                text.push_str(&format!("        evidence = \"{}\";\n", escape_nix(&item.evidence)));
                text.push_str(&format!("        reason = \"{}\";\n", escape_nix(&item.reason)));
                text.push_str("      }\n");
            }
            text.push_str("    ];\n");
        }
        text.push_str("  };");
    }
    text.push_str("\n}");
    text
}

fn render_pyproject(spec: &ProjectSpec) -> String {
    format!(
        r#"[project]
name = "{}"
version = "0.1.0"
requires-python = ">={}"
dependencies = []
"#,
        escape_toml(&spec.env_name),
        escape_toml(&spec.python_version)
    )
}

fn render_list(items: &[String]) -> String {
    items
        .iter()
        .map(|item| format!("    \"{}\"", escape_nix(item)))
        .collect::<Vec<_>>()
        .join("\n")
}

fn escape_nix(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_toml(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}
