use std::fs;
use std::path::Path;
use std::process::{Command, ExitCode, Stdio};

use crate::{Config, combined_output, error, hint, output_with_spinner};

use super::manifest::Manifest;
use super::spec::ProjectSpec;

enum LockStatus {
    Updated,
    Failed(String),
}

pub(super) fn write_project(
    manifest: &Manifest,
    target: &Path,
    flake: &str,
    project: &str,
    spec: &ProjectSpec,
    force: bool,
    source_url: &str,
    config: Config,
) -> Result<(), ExitCode> {
    fs::create_dir_all(target).map_err(|err| {
        error(
            config,
            &format!("failed to create {}: {err}", target.display()),
        );
        ExitCode::from(1)
    })?;

    let flake_path = target.join("flake.nix");
    if flake_path.exists() && !force {
        match fs::read_to_string(&flake_path) {
            Ok(text) if text.contains("mkProjectFlakeFromManifest") => {}
            _ => {
                error(
                    config,
                    &format!(
                        "{} does not look generated by robo-nix",
                        flake_path.display()
                    ),
                );
                hint(
                    config,
                    "rerun with --force only if you want robo to replace it",
                );
                return Err(ExitCode::from(1));
            }
        }
    }

    write_file(&flake_path, flake, config)?;
    write_file(&target.join("robo.nix"), project, config)?;
    write_file(
        &target.join(".python-version"),
        &spec.python_version,
        config,
    )?;
    let pyproject = target.join("pyproject.toml");
    let pyproject_status = if pyproject.exists() {
        "kept"
    } else {
        write_file(&pyproject, &render_pyproject(spec), config)?;
        "wrote"
    };
    let gitignore_status = ensure_gitignore_entry(target, ".robo-nix/", config)?;

    for component in &spec.components {
        let Some(component) = manifest.components.get(component) else {
            continue;
        };
        for dir in &component.scaffold_directories {
            fs::create_dir_all(target.join(dir)).map_err(|err| {
                error(
                    config,
                    &format!("failed to create {}: {err}", target.join(dir).display()),
                );
                ExitCode::from(1)
            })?;
        }
    }

    register_git(
        target,
        &["flake.nix", "robo.nix", ".python-version", "pyproject.toml"],
    );
    if gitignore_status != "kept" {
        register_git(target, &[".gitignore"]);
    }
    let lock_status = update_flake_lock(target, config);
    if matches!(lock_status, LockStatus::Updated) {
        register_git(target, &["flake.lock"]);
    }
    print_summary(
        target,
        spec,
        pyproject_status,
        gitignore_status,
        source_url,
        lock_status,
        config,
    );
    Ok(())
}

fn write_file(path: &Path, text: &str, config: Config) -> Result<(), ExitCode> {
    fs::write(path, format!("{}\n", text.trim_end())).map_err(|err| {
        error(
            config,
            &format!("failed to write {}: {err}", path.display()),
        );
        ExitCode::from(1)
    })
}

fn ensure_gitignore_entry(
    target: &Path,
    entry: &str,
    config: Config,
) -> Result<&'static str, ExitCode> {
    let path = target.join(".gitignore");
    if !path.exists() {
        write_file(&path, entry, config)?;
        return Ok("wrote");
    }

    let text = fs::read_to_string(&path).map_err(|err| {
        error(config, &format!("failed to read {}: {err}", path.display()));
        ExitCode::from(1)
    })?;
    if text.lines().any(|line| line.trim() == entry) {
        return Ok("kept");
    }

    let mut updated = text;
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str(entry);
    updated.push('\n');
    fs::write(&path, updated).map_err(|err| {
        error(
            config,
            &format!("failed to write {}: {err}", path.display()),
        );
        ExitCode::from(1)
    })?;
    Ok("updated")
}

fn register_git(target: &Path, paths: &[&str]) {
    let inside = Command::new("git")
        .arg("-C")
        .arg(target)
        .arg("rev-parse")
        .arg("--is-inside-work-tree")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|status| status.success());
    if inside {
        let _ = Command::new("git")
            .arg("-C")
            .arg(target)
            .args(["add", "--intent-to-add", "--"])
            .args(paths)
            .status();
    }
}

fn update_flake_lock(target: &Path, config: Config) -> LockStatus {
    let mut command = Command::new("nix");
    command
        .arg("flake")
        .arg("lock")
        .arg("--update-input")
        .arg("robo-nix")
        .current_dir(target)
        .stdout(Stdio::null())
        .stderr(Stdio::piped());

    match output_with_spinner(config, &mut command, "updating flake lock") {
        Ok(output) if output.status.success() => LockStatus::Updated,
        Ok(output) => {
            let detail = combined_output(&output);
            let message = detail
                .lines()
                .rev()
                .find(|line| line.trim_start().starts_with("error:"))
                .or_else(|| detail.lines().rev().find(|line| !line.trim().is_empty()))
                .unwrap_or("nix flake lock failed")
                .trim()
                .to_string();
            LockStatus::Failed(message)
        }
        Err(err) => LockStatus::Failed(format!("failed to run nix flake lock: {err}")),
    }
}

fn shell_quote(path: &Path) -> String {
    let text = path.display().to_string();
    format!("'{}'", text.replace('\'', "'\"'\"'"))
}

fn print_summary(
    target: &Path,
    spec: &ProjectSpec,
    pyproject_status: &str,
    gitignore_status: &str,
    source_url: &str,
    lock_status: LockStatus,
    config: Config,
) {
    eprintln!(
        "{} initialized {}",
        crate::label(config, "robo:", crate::LabelKind::Status),
        spec.env_name
    );
    eprintln!();
    crate::section_err(config, "project");
    crate::field_err(config, "directory", &target.display().to_string());
    crate::field_err(config, "runtime", &spec.env_name);
    if config.debug {
        crate::field_err(config, "source", source_url);
    }
    let mut inferred_notes = Vec::new();
    let mut attention_notes = Vec::new();
    for note in &spec.probe_notes {
        if note_needs_attention(note) {
            attention_notes.push(note);
        } else {
            inferred_notes.push(note);
        }
    }

    if !inferred_notes.is_empty() {
        eprintln!();
        crate::section_err(config, "inferred");
        for note in inferred_notes {
            print_inferred_note(config, note);
        }
    }
    print_attention(spec, &attention_notes, config);
    eprintln!();
    crate::section_err(config, "generated");
    print_file_change(config, "wrote", &target.join("flake.nix"));
    print_file_change(config, "wrote", &target.join("robo.nix"));
    print_file_change(config, "wrote", &target.join(".python-version"));
    print_file_change(config, pyproject_status, &target.join("pyproject.toml"));
    print_file_change(config, gitignore_status, &target.join(".gitignore"));
    match lock_status {
        LockStatus::Updated => print_file_change(config, "updated", &target.join("flake.lock")),
        LockStatus::Failed(message) => {
            print_file_change(config, "skipped", &target.join("flake.lock"));
            hint(
                config,
                &format!(
                    "run `(cd {} && nix flake lock --update-input robo-nix)` when Nix is available; {message}",
                    shell_quote(target)
                ),
            );
        }
    }
    eprintln!();
    crate::section_err(config, "next steps");
    if target != Path::new(".") {
        crate::command_row_err(config, &format!("cd {}", shell_quote(target)));
    }
    crate::command_row_err(config, "robo check");
    crate::command_row_err(config, "robo activate");
    crate::command_row_err(config, "uv sync");
}

fn print_file_change(config: Config, action: &str, path: &Path) {
    let action = format!("{action:<7}");
    eprintln!(
        "  {} {}",
        crate::label(config, &action, file_action_kind(action.trim())),
        path.display()
    );
}

fn file_action_kind(action: &str) -> crate::LabelKind {
    match action {
        "wrote" => crate::LabelKind::Ok,
        "updated" | "skipped" => crate::LabelKind::Warn,
        "kept" => crate::LabelKind::Hint,
        _ => crate::LabelKind::Status,
    }
}

fn print_inferred_note(config: Config, note: &str) {
    let (fact, reason) = inferred_note_summary(note);
    let marker = crate::label(config, "✓", crate::LabelKind::Ok);
    match reason {
        Some(reason) => eprintln!("  {marker} {fact:<28} {reason}"),
        None => eprintln!("  {marker} {fact}"),
    }
}

fn note_needs_attention(note: &str) -> bool {
    note.starts_with("skipped bootstrap ")
}

fn inferred_note_summary(note: &str) -> (String, Option<String>) {
    if let Some(rest) = note.strip_prefix("cudaWheelVersion=") {
        if let Some((version, reason)) = rest.split_once(": ") {
            return (format!("CUDA wheel {version}"), Some(reason.to_string()));
        }
    }

    match note {
        "pyproject.toml uses MuJoCo/simulation packages" => (
            "MuJoCo/simulation".to_string(),
            Some("pyproject.toml dependencies".to_string()),
        ),
        "LeRobot workflows commonly need media and graphics runtime libraries" => (
            "media/graphics runtime".to_string(),
            Some("LeRobot workflow".to_string()),
        ),
        "Isaac Sim Python wheels need NVIDIA CUDA and graphics runtime support" => (
            "Isaac Sim runtime".to_string(),
            Some("CUDA and graphics support".to_string()),
        ),
        "workspace contains Qt service paths" => (
            "Qt service paths".to_string(),
            Some("workspace scan".to_string()),
        ),
        _ => match note.split_once(": ") {
            Some((fact, reason)) => (fact.to_string(), Some(reason.to_string())),
            None => (note.to_string(), None),
        },
    }
}

fn print_attention(spec: &ProjectSpec, notes: &[&String], config: Config) {
    if notes.is_empty() && spec.suggestions.is_empty() && spec.component_suggestions.is_empty() {
        return;
    }
    eprintln!();
    crate::section_err(config, "attention");
    for note in notes {
        print_attention_line(config, note);
    }
    for item in &spec.suggestions {
        print_attention_line(
            config,
            &format!("review {} {}: {}", item.kind, item.path, item.reason),
        );
    }
    for item in &spec.component_suggestions {
        print_attention_line(
            config,
            &format!(
                "review component {}: {}; {}",
                item.name, item.reason, item.evidence
            ),
        );
    }
}

fn print_attention_line(config: Config, message: &str) {
    eprintln!(
        "  {} {message}",
        crate::label(config, "!", crate::LabelKind::Warn)
    );
}

pub(super) fn render_flake(source_url: &str) -> String {
    format!(
        r#"{{
  inputs.robo-nix.url = "{}";

  # NOTE: generated plumbing. Most users should edit robo.nix,
  # pyproject.toml, and .python-version instead of this file.
  outputs = {{robo-nix, ...}}:
    robo-nix.lib.mkProjectFlakeFromManifest ./robo.nix;
}}"#,
        escape_nix(source_url)
    )
}

pub(super) fn render_project(spec: &ProjectSpec) -> String {
    let mut text = format!(
        r#"{{
  schemaVersion = 1;
  envName = "{}";
  description = "{}";
  components = [
{}
  ];
  pythonVersion = "{}";
  supportedSystems = [
{}
  ];
  workspaceRoot = "{}";"#,
        escape_nix(&spec.env_name),
        escape_nix(&spec.description),
        render_list(&spec.components),
        escape_nix(&spec.python_version),
        render_list(&spec.supported_systems),
        escape_nix(&spec.workspace_root)
    );
    if let Some(version) = &spec.cuda_wheel_version {
        text.push_str(&format!(
            "\n  cudaWheelVersion = \"{}\";",
            escape_nix(version)
        ));
    }
    if !spec.required_dirs.is_empty() {
        text.push_str(&format!(
            "\n\n  requiredDirectories = [\n{}\n  ];",
            render_list(&spec.required_dirs)
        ));
    }
    if !spec.required_files.is_empty() {
        text.push_str(&format!(
            "\n\n  requiredFiles = [\n{}\n  ];",
            render_list(&spec.required_files)
        ));
    }
    if !spec.env.is_empty() {
        text.push_str("\n\n  shellInit = ''\n");
        for item in &spec.env {
            if let Some((name, value)) = item.split_once('=') {
                text.push_str(&format!("    export {}=\"{}\"\n", name, value));
            }
        }
        text.push_str("  '';");
    }
    if !spec.source_scripts.is_empty() {
        text.push_str("\n\n  bootstrap = ''\n");
        for script in &spec.source_scripts {
            text.push_str(&format!("    . \"$WORKSPACE_ROOT/{}\"\n", script));
        }
        text.push_str("  '';");
    }
    {
        text.push_str("\n\n  provenance = {\n");
        text.push_str("    generatedBy = \"robo init\";\n");
        text.push_str(&format!(
            "    profile = \"{}\";\n",
            escape_nix(&spec.profile_name)
        ));
        if !spec.component_provenance.is_empty() {
            text.push_str("    componentReasons = [\n");
            for item in &spec.component_provenance {
                text.push_str("      {\n");
                text.push_str(&format!("        name = \"{}\";\n", escape_nix(&item.name)));
                text.push_str(&format!(
                    "        source = \"{}\";\n",
                    escape_nix(&item.source)
                ));
                text.push_str(&format!(
                    "        reason = \"{}\";\n",
                    escape_nix(&item.reason)
                ));
                text.push_str("      }\n");
            }
            text.push_str("    ];\n");
        }
        if !spec.probe_notes.is_empty() {
            text.push_str("    inferred = [\n");
            for note in &spec.probe_notes {
                text.push_str(&format!("      \"{}\"\n", escape_nix(note)));
            }
            text.push_str("    ];\n");
        }
        if !spec.source_scripts.is_empty() {
            text.push_str("    sourceScripts = [\n");
            for script in &spec.source_scripts {
                text.push_str(&format!("      \"{}\"\n", escape_nix(script)));
            }
            text.push_str("    ];\n");
        }
        if !spec.suggestions.is_empty() {
            text.push_str("    suggestions = [\n");
            for item in &spec.suggestions {
                text.push_str("      {\n");
                text.push_str(&format!("        kind = \"{}\";\n", escape_nix(&item.kind)));
                text.push_str(&format!("        path = \"{}\";\n", escape_nix(&item.path)));
                text.push_str(&format!(
                    "        reason = \"{}\";\n",
                    escape_nix(&item.reason)
                ));
                text.push_str("      }\n");
            }
            text.push_str("    ];\n");
        }
        if !spec.component_suggestions.is_empty() {
            text.push_str("    componentSuggestions = [\n");
            for item in &spec.component_suggestions {
                text.push_str("      {\n");
                text.push_str(&format!("        name = \"{}\";\n", escape_nix(&item.name)));
                text.push_str(&format!(
                    "        evidence = \"{}\";\n",
                    escape_nix(&item.evidence)
                ));
                text.push_str(&format!(
                    "        reason = \"{}\";\n",
                    escape_nix(&item.reason)
                ));
                text.push_str("      }\n");
            }
            text.push_str("    ];\n");
        }
        text.push_str("  };");
    }
    text.push_str("\n}");
    text
}

fn render_pyproject(spec: &ProjectSpec) -> String {
    format!(
        r#"[project]
name = "{}"
version = "0.1.0"
requires-python = ">={}"
dependencies = []
"#,
        escape_toml(&spec.env_name),
        escape_toml(&spec.python_version)
    )
}

fn render_list(items: &[String]) -> String {
    items
        .iter()
        .map(|item| format!("    \"{}\"", escape_nix(item)))
        .collect::<Vec<_>>()
        .join("\n")
}

fn escape_nix(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_toml(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}
