use std::env;
use std::ffi::OsString;
use std::fs;
use std::path::Path;
use std::process::ExitCode;

use crate::{error, hint, status, Config};

use super::bootstrap::run_bootstrap;
use super::cuda_compat::ensure_runtime_cuda_compat;
use super::nix::{check_command, command_for_runtime, nix_command, run_status};
use super::python::ensure_python_version_files;

pub(crate) fn ensure_project_runtime(config: Config) -> Result<(), ExitCode> {
    if !Path::new("flake.nix").exists() || !Path::new("robo.nix").exists() {
        error(config, "this directory is not initialized for robo-nix.");
        hint(config, "run `robo init .` from the project checkout first.");
        return Err(ExitCode::from(1));
    }
    repair_managed_flake_source(config)?;

    if let Err(message) = check_command("nix") {
        error(config, &message);
        hint(config, "install Nix, then rerun this command.");
        return Err(ExitCode::from(1));
    }

    Ok(())
}

pub(crate) fn run_project_app(mode: Option<&str>, args: Vec<OsString>, config: Config) -> ExitCode {
    if let Err(code) = ensure_project_runtime(config) {
        return code;
    }

    let mut command = nix_command(config);
    command.arg("run").arg(".#default");
    if let Some(mode) = mode {
        command.arg("--").arg(mode);
    }
    command.args(args);
    run_status(&mut command, config)
}

pub(crate) fn run_uv_sync(args: Vec<OsString>, config: Config) -> ExitCode {
    if let Err(code) = prepare_uv_runtime(config, "sync", true) {
        return code;
    }

    status(config, "syncing Python environment");
    // NOTE: uv sync may build native extensions. Run it inside the Nix runtime
    // so compiler and library paths match what the project will use.
    run_status(
        command_for_runtime(config)
            .arg("develop")
            .arg("-c")
            .arg("uv")
            .arg("sync")
            .args(args),
        config,
    )
}

pub(crate) fn run_project_shell(args: Vec<OsString>, config: Config) -> ExitCode {
    if let Err(code) = prepare_runtime(config, false) {
        return code;
    }

    run_status(
        command_for_runtime(config)
            .arg("develop")
            .args(normalize_shell_args(args)),
        config,
    )
}

pub(crate) fn run_project_command(args: Vec<OsString>, config: Config) -> ExitCode {
    if args.is_empty() {
        error(config, "run needs a command.");
        hint(config, "example: robo run pytest tests");
        return ExitCode::from(2);
    }

    if let Err(code) = prepare_uv_runtime(config, "run", true) {
        return code;
    }

    let args = if args.first().is_some_and(|arg| arg == "uv")
        && args.get(1).is_some_and(|arg| arg == "run")
    {
        args.into_iter().skip(2).collect()
    } else {
        args
    };

    run_status(
        command_for_runtime(config)
            .arg("develop")
            .arg("-c")
            .arg("uv")
            .arg("run")
            .args(args),
        config,
    )
}

fn prepare_uv_runtime(config: Config, command_name: &str, cuda_strict: bool) -> Result<(), ExitCode> {
    ensure_pyproject(config, command_name)?;
    ensure_python_version_files(config)?;
    prepare_runtime(config, cuda_strict)
}

fn prepare_runtime(config: Config, cuda_strict: bool) -> Result<(), ExitCode> {
    ensure_project_runtime(config)?;
    run_bootstrap(config)?;
    ensure_runtime_cuda_compat(config, cuda_strict)
}

fn ensure_pyproject(config: Config, command_name: &str) -> Result<(), ExitCode> {
    if Path::new("pyproject.toml").exists() {
        return Ok(());
    }
    error(config, &format!("{command_name} needs pyproject.toml."));
    hint(config, "run `robo init .` or create pyproject.toml for uv.");
    Err(ExitCode::from(1))
}

fn repair_managed_flake_source(config: Config) -> Result<(), ExitCode> {
    let flake_path = Path::new("flake.nix");
    let flake = match fs::read_to_string(flake_path) {
        Ok(flake) => flake,
        Err(err) => {
            error(config, &format!("failed to read flake.nix: {err}"));
            return Err(ExitCode::from(1));
        }
    };
    if !flake.contains("mkProjectFlakeFromManifest") {
        error(config, "flake.nix does not look generated by robo.");
        hint(
            config,
            "run `robo init . --force` only if you want robo to replace this flake.",
        );
        return Err(ExitCode::from(1));
    }
    if !flake.contains("github:ausbxuse/robo-nix") {
        return Ok(());
    }

    let source_url = match env::var("ROBO_NIX_DEFAULT_SOURCE_URL") {
        Ok(source_url) => source_url,
        Err(_) => {
            error(
                config,
                "flake.nix points at github:ausbxuse/robo-nix, but this robo install has no packaged source URL.",
            );
            hint(
                config,
                "run `robo init . --robo-nix-url path:/path/to/robo-nix` to repair this project.",
            );
            return Err(ExitCode::from(1));
        }
    };
    let repaired = flake.replace("github:ausbxuse/robo-nix", &source_url);
    if let Err(err) = fs::write(flake_path, repaired) {
        error(config, &format!("failed to repair flake.nix: {err}"));
        return Err(ExitCode::from(1));
    }
    status(config, &format!("repaired flake.nix to use {source_url}"));
    Ok(())
}

fn normalize_shell_args(mut args: Vec<OsString>) -> Vec<OsString> {
    if args.is_empty() {
        return default_interactive_shell_args();
    }

    if args.len() != 2 || args[0] != "-c" {
        return args;
    }

    if !args[1].to_string_lossy().chars().any(char::is_whitespace) {
        return args;
    }

    let mut normalized = Vec::with_capacity(4);
    normalized.push(OsString::from("-c"));
    normalized.push(OsString::from("bash"));
    normalized.push(OsString::from("-lc"));
    normalized.push(args.swap_remove(1));
    normalized
}

fn default_interactive_shell_args() -> Vec<OsString> {
    let Ok(shell) = env::var("SHELL") else {
        return Vec::new();
    };
    shell_args_for(&shell)
}

fn shell_args_for(shell: &str) -> Vec<OsString> {
    if shell.is_empty() || !Path::new(shell).is_file() {
        return Vec::new();
    }
    vec![OsString::from("-c"), OsString::from(shell), OsString::from("-l")]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsString;

    #[test]
    fn shell_command_with_single_quoted_string_uses_shell() {
        let args = vec![OsString::from("-c"), OsString::from("python test.py")];
        let normalized = normalize_shell_args(args);
        let values: Vec<_> = normalized
            .iter()
            .map(|arg| arg.to_string_lossy().into_owned())
            .collect();

        assert_eq!(values, vec!["-c", "bash", "-lc", "python test.py"]);
    }

    #[test]
    fn shell_command_without_args_uses_user_shell() {
        let normalized = shell_args_for("/bin/sh");
        let values: Vec<_> = normalized
            .iter()
            .map(|arg| arg.to_string_lossy().into_owned())
            .collect();

        assert_eq!(values, vec!["-c", "/bin/sh", "-l"]);
    }

    #[test]
    fn shell_command_keeps_split_argv_intact() {
        let args = vec![
            OsString::from("-c"),
            OsString::from("python"),
            OsString::from("test.py"),
        ];
        let normalized = normalize_shell_args(args.clone());
        let values: Vec<_> = normalized
            .iter()
            .map(|arg| arg.to_string_lossy().into_owned())
            .collect();

        assert_eq!(values, vec!["-c", "python", "test.py"]);
        assert_eq!(normalized, args);
    }
}
